### ISSUE TITLE
>ERR) Could not read file <ahy.fasta

### ISSUE THREAD

**Issue by sujee119** [kcri-tz/sans#1]
Hi,
Thank you for the package and the youtube tutorial. I'm new to run packages so please bare with me. 

I have installed SANS and try to run the analysis for both AA seqs and whole chromosomes. It apprears the list text file does not recognize the fileset properly. My file information follows,

Fasta file list:

/home/cyborg/sans/example_data/root_hair/fasta/ahy.fasta
/home/cyborg/sans/example_data/root_hair/fasta/ath.fasta
/home/cyborg/sans/example_data/root_hair/fasta/bdi.fasta
/home/cyborg/sans/example_data/root_hair/fasta/bol.fasta
/home/cyborg/sans/example_data/root_hair/fasta/cpur.fasta
/home/cyborg/sans/example_data/root_hair/fasta/crei.fasta
/home/cyborg/sans/example_data/root_hair/fasta/cric.fasta
/home/cyborg/sans/example_data/root_hair/fasta/dcomp.fasta
/home/cyborg/sans/example_data/root_hair/fasta/dsal.fasta
/home/cyborg/sans/example_data/root_hair/fasta/gmax.fasta
/home/cyborg/sans/example_data/root_hair/fasta/ljap.fasta
/home/cyborg/sans/example_data/root_hair/fasta/mpol.fasta
/home/cyborg/sans/example_data/root_hair/fasta/mtru.fasta
/home/cyborg/sans/example_data/root_hair/fasta/oluc.fasta
/home/cyborg/sans/example_data/root_hair/fasta/osat.fasta
/home/cyborg/sans/example_data/root_hair/fasta/ppat.fasta
/home/cyborg/sans/example_data/root_hair/fasta/sfal.fasta
/home/cyborg/sans/example_data/root_hair/fasta/slyc.fasta
/home/cyborg/sans/example_data/root_hair/fasta/smoe.fasta
/home/cyborg/sans/example_data/root_hair/fasta/stub.fasta
/home/cyborg/sans/example_data/root_hair/fasta/vcar.fasta

Genomelist file:
/home/cyborg/sans/example_data/root_hair/fasta/genomelist.txt

Genome list contents
ahy.fasta
ath.fasta
bdi.fasta
bol.fasta
cpur.fasta
crei.fasta
cric.fasta
dcomp.fasta
dsal.fasta
gmax.fasta
ljap.fasta
mpol.fasta
mtru.fasta
oluc.fasta
osat.fasta
ppat.fasta
sfal.fasta
slyc.fasta
smoe.fasta
stub.fasta
vcar.fasta

When i run the codes;

(sans) cyborg@skynet:~/sans/example_data/root_hair/genome$ SANS -i genomelist.txt -o sans.splits -t 10n -f weakly
>ERR) Could not read file <ahy.fa

Please help,
~Sujeevan

**Comment by zwets** [comment]
Better report this at [the upstream repository](https://gitlab.ub.uni-bielefeld.de/gi/sans.git). The repository you have cloned is a (slightly modified) fork of that SANS repository, which is maintained by SANS's author.

**Comment by sujee119** [comment]
> Better report this at [the upstream repository](https://gitlab.ub.uni-bielefeld.de/gi/sans.git). The repository you have cloned is a (slightly modified) fork of that SANS repository, which is maintained by SANS's author.

Thank you for the response. the same error popped up when i clone this repository too in a different machine. Btw, i don't have a work email, so i can't log in to the upstream repository. Please note and i really appreciate your assistance.
