### ISSUE TITLE
Nexus files are not opened by Splitstree and pdf are not created

### ISSUE THREAD

**Issue by matdechiara** [kcri-tz/sans#2]
Hi, 
I have run the command 

SANS -i isolates_paths.txt -o splitfile -v -T 10 

and i I get a file with 255 lines, with in each row a number and then a list of filenames.

However when I create a nexus from that  (sans2nexus.py splitfile isolates_paths.txt) and I try to open it with splitstree ( 4 or 6 ) I get errors. Actrually, the v6 doesn't  do anything, while the v4 give this error: 
"Import failed: unknown format or erro in file (e.g. illegal charachters or multiple occurrences of same taxon name)."

sans is on a linux server, Splitstree on a mac, so I installed the Splitstree also on the server, but if I use the command to create the pdf (sans2pdf.py splitfile isolates_paths.txt ) only the nexus is creted, without any error reported.

**Comment by zwets** [comment]
Better report this at [the upstream repository](https://gitlab.ub.uni-bielefeld.de/gi/sans.git). The repository you have cloned is a (modified and out of date) fork of that SANS repository.
