### ISSUE TITLE
Absolute paths unrecognised

### ISSUE THREAD

**Issue by cmfield** [kcri-tz/sans#3]
I have a kmtricks file I am using as input:

`<name>: /absolute/path/to/fasta
`
However it is not recognising the path as absolute and appending it to my working directory.

**Comment by cmfield** [comment]
Just adding that the absolute paths *do* work if the kmtricks file is in my working directory.. so SANS is making weird assumptions ..

**Comment by zwets** [comment]
Hi Chris, better report this at [the upstream repository](https://gitlab.ub.uni-bielefeld.de/gi/sans.git). The repository you have cloned is a (modified and slighly out of date) fork of that SANS repository. Cheers, Marco

**Comment by cmfield** [comment]
It appears to have been fixed in the new version - thanks :)
